
"""
app/services/processing/processing_service.py

Application service responsible for the lifecycle of document
processing jobs.

Architecture:

    API
      |
      v
    ProcessingService
      |
      +--> validate Document
      +--> resolve DocumentVersion
      +--> create ProcessingJob
      +--> create ProcessingStep records
      |
      v
    ProcessingJobRunner
      |
      +--> StageRegistry
      +--> StorageService
      |
      v
    DocumentProcessor
      |
      v
    Pipeline
      |
      +--> classification
      +--> layout_analysis
      +--> text_extraction
      +--> ocr
      +--> structure_detection
      +--> cleaning
      +--> chunking
      +--> metadata_enrichment
      +--> embedding
      +--> indexing

Document Intelligence Result:

    ProcessingJob.result

contains the structured output generated by the pipeline.

ProcessingService owns job lifecycle.
ProcessingJobRunner owns execution.
Pipeline stages own document intelligence logic.

IMPORTANT ARCHITECTURE NOTE
---------------------------

StageRegistry is optional because the web process only needs to:

    - create processing jobs
    - create processing steps
    - inspect processing status
    - cancel jobs
    - retrieve results

The heavy StageRegistry, including the Hugging Face BGE embedding
model, is constructed only inside the dedicated worker process.

Actual pipeline execution therefore requires:

    stage_registry != None
"""

from __future__ import annotations

import logging
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.constants import ProcessingStage
from app.db.models.document import Document
from app.db.models.document_version import DocumentVersion
from app.db.models.processing_job import ProcessingJob
from app.db.models.processing_step import ProcessingStep

from app.processing.stage_registry import StageRegistry
from app.processing.job_runner import ProcessingJobRunner
from app.storage.service import StorageService


logger = logging.getLogger(__name__)


class ProcessingService:
    """
    Application-level service for document processing.

    Responsibilities:

        - validate documents
        - resolve document versions
        - create processing jobs
        - create processing steps
        - execute processing jobs
        - inspect processing status
        - retrieve Document Intelligence results
        - cancel processing jobs

    Individual processing stages are NOT implemented here.

    StageRegistry is optional because job creation and job inspection
    must remain lightweight and must not load the embedding model.

    Actual pipeline execution requires StageRegistry and is performed
    by the worker process.
    """

    def __init__(
        self,
        db: AsyncSession,
        storage_service: StorageService,
        stage_registry: StageRegistry | None = None,
    ) -> None:
        self.db = db
        self.storage_service = storage_service
        self.stage_registry = stage_registry

    # ========================================================================
    # START PROCESSING
    # ========================================================================

    async def start_processing(
        self,
        document_id: UUID,
        force: bool = False,
    ) -> ProcessingJob:
        """
        Create a processing job.

        This method does not execute the pipeline.

        Pipeline execution is scheduled separately by the API.

        IMPORTANT:
        This method intentionally does not validate or construct the
        StageRegistry. The web process only needs the canonical
        ProcessingStage enum to create processing-step records.

        Actual StageRegistry construction and pipeline execution belong
        to the worker process.
        """

        # ------------------------------------------------------------------
        # Load document
        # ------------------------------------------------------------------

        result = await self.db.execute(
            select(Document)
            .where(
                Document.id == document_id,
            )
            .options(
                selectinload(Document.versions),
            )
        )

        document = result.scalar_one_or_none()

        if document is None:
            raise ValueError(
                f"Document {document_id} was not found."
            )

        # ------------------------------------------------------------------
        # Resolve document version
        # ------------------------------------------------------------------

        document_version = await self._get_document_version(
            document=document,
        )

        if document_version is None:
            raise ValueError(
                "Document does not have an uploaded version."
            )

        # ------------------------------------------------------------------
        # Validate storage artifact
        # ------------------------------------------------------------------

        if not document_version.object_storage_bucket:
            raise ValueError(
                f"DocumentVersion {document_version.id} does not have "
                "an object storage bucket."
            )

        if not document_version.object_storage_key:
            raise ValueError(
                f"DocumentVersion {document_version.id} does not have "
                "an object storage key."
            )

        # ------------------------------------------------------------------
        # Existing job
        # ------------------------------------------------------------------

        if not force:

            existing_job = await self._get_existing_job(
                document_version_id=document_version.id,
            )

            if existing_job is not None:

                existing_status = self._status_value(
                    existing_job.status
                )

                if existing_status in {
                    "queued",
                    "running",
                    "processing",
                }:
                    return existing_job

                if existing_status == "completed":
                    return existing_job

        # ------------------------------------------------------------------
        # Create ProcessingJob
        # ------------------------------------------------------------------

        job = ProcessingJob(
            document_version_id=document_version.id,
            job_type="document_processing",
            status="queued",
            priority=0,
            attempt_count=0,
            max_attempts=3,
            current_step=None,
            progress=0,
            config={
                "ocr_enabled": True,
                "classification_enabled": True,
                "extraction_enabled": True,
                "chunking_enabled": True,
                "embeddings_enabled": True,
                "indexing_enabled": True,
                "document_intelligence_result_enabled": True,
            },
            result={
                "schema_version": "1.0",
                "status": "pending",
                "document": {
                    "document_id": str(document.id),
                    "document_version_id": str(
                        document_version.id
                    ),
                },
                "stages": {},
            },
        )

        self.db.add(job)

        await self.db.flush()

        # ------------------------------------------------------------------
        # Create processing steps
        # ------------------------------------------------------------------

        await self._create_steps(
            job=job,
        )

        await self.db.flush()

        logger.info(
            "Created processing job",
            extra={
                "processing_job_id": str(job.id),
                "document_id": str(document_id),
                "document_version_id": str(
                    document_version.id
                ),
                "pipeline_stages": [
                    stage.value
                    for stage in ProcessingStage
                ],
            },
        )

        # ------------------------------------------------------------------
        # Commit job creation
        # ------------------------------------------------------------------

        await self.db.commit()

        await self.db.refresh(job)

        return job

    # ========================================================================
    # EXECUTE PROCESSING JOB
    # ========================================================================

    async def execute_processing_job(
        self,
        job_id: UUID,
    ) -> ProcessingJob:
        """
        Execute an already-created processing job.

        ProcessingJobRunner owns actual pipeline execution.

        This method is intended for the worker process, where the
        StageRegistry and heavy processing dependencies are available.

        The web process must never call this method without a
        StageRegistry.
        """

        # ------------------------------------------------------------------
        # StageRegistry is required for actual pipeline execution
        # ------------------------------------------------------------------

        if self.stage_registry is None:
            raise RuntimeError(
                "StageRegistry is required to execute a processing job."
            )

        # ------------------------------------------------------------------
        # Build runner
        # ------------------------------------------------------------------

        runner = ProcessingJobRunner(
            db=self.db,
            stage_registry=self.stage_registry,
            storage_service=self.storage_service,
        )

        try:

            job = await runner.run(
                job_id=job_id,
            )

            logger.info(
                "Processing job execution finished",
                extra={
                    "processing_job_id": str(job_id),
                    "status": self._status_value(
                        job.status
                    ),
                    "progress": getattr(
                        job,
                        "progress",
                        None,
                    ),
                },
            )

            return job

        except Exception:

            logger.exception(
                "Processing job execution failed",
                extra={
                    "processing_job_id": str(job_id),
                },
            )

            raise

    # ========================================================================
    # GET STATUS
    # ========================================================================

    async def get_processing_status(
        self,
        processing_id: UUID,
    ) -> ProcessingJob | None:
        """
        Return a processing job with its version and steps.
        """

        result = await self.db.execute(
            select(ProcessingJob)
            .where(
                ProcessingJob.id == processing_id,
            )
            .options(
                selectinload(
                    ProcessingJob.steps,
                ),
                selectinload(
                    ProcessingJob.document_version,
                ),
            )
        )

        return result.scalar_one_or_none()

    # ========================================================================
    # GET DOCUMENT INTELLIGENCE RESULT
    # ========================================================================

    async def get_processing_result(
        self,
        processing_id: UUID,
    ) -> ProcessingJob | None:
        """
        Return the processing job containing the persisted
        Document Intelligence Result.

        The result is stored in:

            ProcessingJob.result

        The canonical DocumentIntelligenceResult is persisted separately
        by ProcessingJobRunner.
        """

        result = await self.db.execute(
            select(ProcessingJob)
            .where(
                ProcessingJob.id == processing_id,
            )
            .options(
                selectinload(
                    ProcessingJob.document_version,
                ),
                selectinload(
                    ProcessingJob.steps,
                ),
            )
        )

        return result.scalar_one_or_none()

    # ========================================================================
    # CANCEL
    # ========================================================================

    async def cancel_processing(
        self,
        processing_id: UUID,
    ) -> ProcessingJob | None:
        """
        Cancel a processing job.

        Completed and failed jobs cannot be cancelled.
        """

        job = await self.get_processing_status(
            processing_id=processing_id,
        )

        if job is None:
            return None

        status = self._status_value(
            job.status
        )

        # ------------------------------------------------------------------
        # Already completed
        # ------------------------------------------------------------------

        if status == "completed":
            raise ValueError(
                "Completed processing jobs cannot be cancelled."
            )

        # ------------------------------------------------------------------
        # Already failed
        # ------------------------------------------------------------------

        if status == "failed":
            raise ValueError(
                "Failed processing jobs cannot be cancelled."
            )

        # ------------------------------------------------------------------
        # Already cancelled
        # ------------------------------------------------------------------

        if status == "cancelled":
            return job

        # ------------------------------------------------------------------
        # Mark cancelled
        # ------------------------------------------------------------------

        job.status = "cancelled"

        if hasattr(
            job,
            "error_code",
        ):
            job.error_code = None

        if hasattr(
            job,
            "error_message",
        ):
            job.error_message = None

        # ------------------------------------------------------------------
        # Cancel current processing step
        # ------------------------------------------------------------------

        current_step = getattr(
            job,
            "current_step",
            None,
        )

        if current_step:

            for step in job.steps:

                step_name = getattr(
                    step,
                    "name",
                    None,
                )

                step_status = self._status_value(
                    getattr(
                        step,
                        "status",
                        None,
                    )
                )

                if step_name == current_step:

                    if step_status in {
                        "queued",
                        "running",
                        "processing",
                        "pending",
                    }:
                        step.status = "cancelled"

                    break

        # ------------------------------------------------------------------
        # Update ProcessingJob.result metadata
        # ------------------------------------------------------------------

        current_result = getattr(
            job,
            "result",
            None,
        )

        if not isinstance(
            current_result,
            dict,
        ):
            current_result = {}

        current_result["status"] = "cancelled"

        job.result = current_result

        await self.db.commit()

        await self.db.refresh(
            job
        )

        logger.info(
            "Processing job cancelled",
            extra={
                "processing_job_id": str(
                    job.id
                ),
            },
        )

        return job

    # ========================================================================
    # DOCUMENT VERSION
    # ========================================================================

    async def _get_document_version(
        self,
        document: Document,
    ) -> DocumentVersion | None:
        """
        Resolve the version that should be processed.

        Priority:

            1. current_version_id
            2. highest version_number from loaded versions
            3. database fallback
        """

        current_version_id = getattr(
            document,
            "current_version_id",
            None,
        )

        # ------------------------------------------------------------------
        # Current version
        # ------------------------------------------------------------------

        if current_version_id is not None:

            result = await self.db.execute(
                select(DocumentVersion)
                .where(
                    DocumentVersion.id
                    == current_version_id,
                )
            )

            version = result.scalar_one_or_none()

            if version is not None:
                return version

        # ------------------------------------------------------------------
        # Loaded versions
        # ------------------------------------------------------------------

        versions = getattr(
            document,
            "versions",
            None,
        )

        if versions:

            valid_versions = [
                version
                for version in versions
                if version is not None
            ]

            if valid_versions:

                return max(
                    valid_versions,
                    key=lambda version: (
                        version.version_number
                    ),
                )

        # ------------------------------------------------------------------
        # Database fallback
        # ------------------------------------------------------------------

        result = await self.db.execute(
            select(DocumentVersion)
            .where(
                DocumentVersion.document_id
                == document.id,
            )
            .order_by(
                DocumentVersion.version_number.desc(),
            )
            .limit(1)
        )

        return result.scalar_one_or_none()

    # ========================================================================
    # EXISTING JOB
    # ========================================================================

    async def _get_existing_job(
        self,
        document_version_id: UUID,
    ) -> ProcessingJob | None:
        """
        Find the most recent processing job for a document version.
        """

        result = await self.db.execute(
            select(ProcessingJob)
            .where(
                ProcessingJob.document_version_id
                == document_version_id
            )
            .order_by(
                ProcessingJob.created_at.desc(),
            )
            .limit(1)
        )

        return result.scalar_one_or_none()

    # ========================================================================
    # CREATE STEPS
    # ========================================================================

    async def _create_steps(
        self,
        job: ProcessingJob,
    ) -> list[ProcessingStep]:
        """
        Create processing-step history records.

        The canonical stage identifiers come from ProcessingStage rather
        than StageRegistry so that creating a job does not require the
        heavy processing registry or embedding model.
        """

        steps: list[ProcessingStep] = []

        for index, stage in enumerate(
            ProcessingStage,
            start=1,
        ):

            stage_name = stage.value

            step = ProcessingStep(
                processing_job_id=job.id,
                name=stage_name,
                step_order=index,
                status="pending",
                attempt_count=0,
                input_metadata={},
                output_metadata={},
            )

            self.db.add(
                step
            )

            steps.append(
                step
            )

        if not steps:
            raise RuntimeError(
                "No processing stages are registered."
            )

        return steps

    # ========================================================================
    # STATUS HELPER
    # ========================================================================

    @staticmethod
    def _status_value(
        status: object,
    ) -> str:
        """
        Normalize enum/string status values.
        """

        if status is None:
            return ""

        value = getattr(
            status,
            "value",
            status,
        )

        return str(
            value
        ).strip().lower()


__all__ = [
    "ProcessingService",
]

