"""
app/schemas/knowledge/search_schema.py

Pydantic schemas for Knowledge Search.

Supported search modes:

    semantic
    keyword
    hybrid

The schemas are intentionally independent from the database models.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
)


# ============================================================================
# SEARCH TYPE
# ============================================================================

SearchType = Literal[
    "semantic",
    "keyword",
    "hybrid",
]


# ============================================================================
# SEARCH REQUEST
# ============================================================================


class SearchRequest(BaseModel):
    """
    Knowledge search request.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    query: str = Field(
        ...,
        min_length=1,
        max_length=10_000,
        description="Natural-language search query.",
    )

    collection_id: UUID | None = Field(
        default=None,
        description="Optional knowledge collection constraint.",
    )

    search_type: SearchType = Field(
        default="hybrid",
        description="semantic | keyword | hybrid",
    )

    top_k: int = Field(
        default=10,
        ge=1,
        le=100,
        description="Maximum number of final search results.",
    )

    score_threshold: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Minimum relevance score.",
    )

    filters: dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata filters.",
    )

    include_metadata: bool = Field(
        default=True,
        description="Whether result metadata should be returned.",
    )

    rerank: bool = Field(
        default=True,
        description="Whether retrieved results should be reranked.",
    )

    @field_validator(
        "query"
    )
    @classmethod
    def validate_query(
        cls,
        value: str,
    ) -> str:
        """
        Normalize and validate the query.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Search query cannot be empty."
            )

        return value

    @field_validator(
        "filters"
    )
    @classmethod
    def validate_filters(
        cls,
        value: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Validate metadata filter keys.
        """

        for key in value:

            if not isinstance(
                key,
                str,
            ):
                raise ValueError(
                    "Filter keys must be strings."
                )

            key = key.strip()

            if not key:
                raise ValueError(
                    "Filter keys cannot be empty."
                )

        return value


# ============================================================================
# SEARCH RESULT
# ============================================================================


class SearchResult(BaseModel):
    """
    Single knowledge-search result.
    """

    model_config = ConfigDict(
        from_attributes=True
    )

    chunk_id: UUID | str | None = Field(
        default=None,
        description="Chunk identifier.",
    )

    document_id: UUID | str | None = Field(
        default=None,
        description="Source document identifier.",
    )

    collection_id: UUID | str | None = Field(
        default=None,
        description="Knowledge collection identifier.",
    )

    content: str = Field(
        default="",
        description="Retrieved chunk content.",
    )

    score: float = Field(
        default=0.0,
        description="Final relevance score.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Chunk metadata.",
    )

    # Optional scores generated by HybridSearch.
    semantic_score: float | None = Field(
        default=None,
        description="Semantic retrieval score.",
    )

    keyword_score: float | None = Field(
        default=None,
        description="Keyword retrieval score.",
    )


# ============================================================================
# SEARCH RESPONSE
# ============================================================================


class SearchResponse(BaseModel):
    """
    Search API response.

    Matches SearchService.search():

        {
            "query": "...",
            "total_results": 10,
            "elapsed_ms": 23.4,
            "search_type": "hybrid",
            "results": [...]
        }
    """

    model_config = ConfigDict(
        from_attributes=True
    )

    query: str

    total_results: int = Field(
        ge=0
    )

    elapsed_ms: float = Field(
        ge=0.0
    )

    search_type: SearchType

    results: list[SearchResult] = Field(
        default_factory=list
    )


# ============================================================================
# SEARCH HISTORY
# ============================================================================


class SearchHistoryResponse(BaseModel):
    """
    Search-history item.
    """

    model_config = ConfigDict(
        from_attributes=True
    )

    id: UUID

    user_id: UUID

    query: str

    search_type: SearchType

    result_count: int = Field(
        ge=0
    )

    latency_ms: float = Field(
        ge=0.0
    )

    created_at: datetime


__all__ = [
    "SearchType",
    "SearchRequest",
    "SearchResult",
    "SearchResponse",
    "SearchHistoryResponse",
]