"""register processing and intelligence models

Revision ID: cf6c0d08bf07
Revises: b35652cc2a5a
Create Date: 2026-09-02 18:32:54.376197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6c0d08bf07'
down_revision: Union[str, Sequence[str], None] = 'b35652cc2a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_result_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_result_id'], ['extraction_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_extraction_result_id'), 'validation_results', ['extraction_result_id'], unique=False)
    op.create_index(op.f('ix_validation_results_field_name'), 'validation_results', ['field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_field_name'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_extraction_result_id'), table_name='validation_results')
    op.drop_table('validation_results')
    # ### end Alembic commands ###
