"""
Base output model for workflow nodes.

NodeOutput represents the successful output generated by a node.
Execution-related information such as success, errors, and duration
is handled separately by NodeResult.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class NodeOutput:
    """
    Output produced by a workflow node.

    Attributes:
        data:
            Primary output payload.

        artifacts:
            Additional outputs such as files, images,
            embeddings, tables, etc.

        variables:
            Workflow variables that should be merged
            into the shared NodeContext.

        metadata:
            Optional node-specific metadata.
    """

    data: Any = None

    artifacts: dict[str, Any] = field(default_factory=dict)

    variables: dict[str, Any] = field(default_factory=dict)

    metadata: dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Artifacts
    # ------------------------------------------------------------------

    def add_artifact(self, name: str, value: Any) -> None:
        """Register an output artifact."""
        self.artifacts[name] = value

    def get_artifact(self, name: str, default: Any = None) -> Any:
        """Retrieve an artifact."""
        return self.artifacts.get(name, default)

    # ------------------------------------------------------------------
    # Variables
    # ------------------------------------------------------------------

    def add_variable(self, name: str, value: Any) -> None:
        """Export a workflow variable."""
        self.variables[name] = value

    def get_variable(self, name: str, default: Any = None) -> Any:
        """Retrieve an exported variable."""
        return self.variables.get(name, default)

    # ------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------

    def add_metadata(self, name: str, value: Any) -> None:
        """Attach metadata to the output."""
        self.metadata[name] = value

    def get_metadata(self, name: str, default: Any = None) -> Any:
        """Retrieve metadata."""
        return self.metadata.get(name, default)

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    @property
    def has_artifacts(self) -> bool:
        """Return True if artifacts are present."""
        return bool(self.artifacts)

    @property
    def has_variables(self) -> bool:
        """Return True if workflow variables are present."""
        return bool(self.variables)

    def to_dict(self) -> dict[str, Any]:
        """Serialize the output."""
        return {
            "data": self.data,
            "artifacts": self.artifacts,
            "variables": self.variables,
            "metadata": self.metadata,
        }